name: Build & Release ScrapeWeb

# Run whenever you push a semver tag, e.g. v2.1.2
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build & Publish Release
        run: npm run dist -- --publish always
